version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.7.14-management
    container_name: rabbitmq2
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - 5672:5672
      - 15672:15672
  is2-workflow-monitor:
    image: mecdcme/is2-workflow-monitor:latest
    ports:
      - 8081:8081
    environment:
      - SERVER_PORT=8080
      - SPRING_RABBITMQ_HOST=rabbitmq2
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres?currentSchema=is2
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_DATASOURCE_PLATFORM=postgresql
      - EUREKA_CLIENT_INSTANCE_HOSTNAME=eureka-server
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://is2-api-gateway:8080/eureka
    depends_on:
      - db
      - rabbitmq
      - is2-api-gateway
    restart: always
  is2-logger:
    image: mecdcme/is2-logger:latest
    ports:
      - 8082:8082
    environment:
      - SERVER_PORT=8080
      - SPRING_RABBITMQ_HOST=rabbitmq2
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres?currentSchema=is2
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_DATASOURCE_PLATFORM=postgresql
      - EUREKA_CLIENT_INSTANCE_HOSTNAME=eureka-server
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://is2-api-gateway:8080/eureka
    depends_on:
      - db
      - rabbitmq
      - is2-api-gateway
    restart: always
  is2-dataset:
    image: mecdcme/is2-dataset:latest
    ports:
      - 8083:8083
    environment:
      - SERVER_PORT=8080
      - SPRING_RABBITMQ_HOST=rabbitmq2
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres?currentSchema=is2
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_DATASOURCE_PLATFORM=postgresql
      - EUREKA_CLIENT_INSTANCE_HOSTNAME=eureka-server
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://is2-api-gateway:8080/eureka
    depends_on:
      - db
      - rabbitmq
      - is2-api-gateway
    restart: always
  is2-notificator:
    image: mecdcme/is2-notificator:latest
    ports:
      - 8084:8084
    environment:
      - SERVER_PORT=8080
      - SPRING_RABBITMQ_HOST=rabbitmq2
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres?currentSchema=is2_notificator
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_DATASOURCE_PLATFORM=postgresql
      - EUREKA_CLIENT_INSTANCE_HOSTNAME=eureka-server
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://is2-api-gateway:8080/eureka
    depends_on:
      - db
      - rabbitmq
      - is2-api-gateway
    restart: always    
  is2-api-gateway:
    image: mecdcme/is2-api-gateway:latest
    ports:
      - 8080:8080
    restart: always      
  db:
    image: mecdcme/is2-postgres:dev
    environment:
      - POSTGRES_PASSWORD=postgres
