version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.7.14-management
    deploy:
      resources:
        limits:
          memory: 1024M
    container_name: rabbitmq2
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - 5672:5672
      - 15672:15672  
  db:
    image: mecdcme/is2-postgres:dev
    deploy:
      resources:
        limits:
          memory: 1024M
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  is2-api-gateway:
    image: mecdcme/is2-api-gateway:latest
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres?currentSchema=is2
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_DATASOURCE_PLATFORM=postgresql
      - ZUUL_ROUTES_SERVICE_WORKFLOW_STATUS_URL=http://is2-workflow-monitor:8081/monitor
      - ZUUL_ROUTES_SERVICE_LOGGER_URL=http://is2-logger:8082/log
      - ZUUL_ROUTES_SERVICE_DATASET_URL=http://is2-dataset:8083/dataset
      - ZUUL_ROUTES_SERVICE_NOTIFICATOR_URL=http://is2-notificator:8084/notificator
      - ZUUL_ROUTES_SERVICE_RUNTIME_URL=http://is2-runtime:8085/runtime
      - ZUUL_ROUTES_SERVICE_DESIGN_URL=http://is2-design:8086/design