version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.7.14-management
    deploy:
      resources:
        limits:
          memory: 1024M
    container_name: rabbitmq2
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - 5672:5672
      - 15672:15672  
  db:
    image: mecdcme/is2-postgres:dev
    deploy:
      resources:
        limits:
          memory: 1024M
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data