version: '3'
services:
  is2-workflow-monitor:
    image: mecdcme/is2-workflow-monitor:latest
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - 8081:8081
    environment:
      - SERVER_PORT=8081
      - SPRING_RABBITMQ_HOST=rabbitmq2
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres?currentSchema=is2
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_DATASOURCE_PLATFORM=postgresql
      - EUREKA_CLIENT_INSTANCE_HOSTNAME=eureka-server
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://is2-api-gateway:8080/eureka
  is2-logger:
    image: mecdcme/is2-logger:latest
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - 8082:8082
    environment:
      - SERVER_PORT=8082
      - SPRING_RABBITMQ_HOST=rabbitmq2
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres?currentSchema=is2
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_DATASOURCE_PLATFORM=postgresql
      - EUREKA_CLIENT_INSTANCE_HOSTNAME=eureka-server
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://is2-api-gateway:8080/eureka
  is2-dataset:
    image: mecdcme/is2-dataset:latest
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - 8083:8083
    environment:
      - SERVER_PORT=8083
      - SPRING_RABBITMQ_HOST=rabbitmq2
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres?currentSchema=is2
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_DATASOURCE_PLATFORM=postgresql
      - EUREKA_CLIENT_INSTANCE_HOSTNAME=eureka-server
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://is2-api-gateway:8080/eureka
  is2-notificator:
    image: mecdcme/is2-notificator:latest
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - 8084:8084
    environment:
      - SERVER_PORT=8084
      - SPRING_RABBITMQ_HOST=rabbitmq2
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres?currentSchema=is2_notificator
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_DATASOURCE_PLATFORM=postgresql
      - EUREKA_CLIENT_INSTANCE_HOSTNAME=eureka-server
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://is2-api-gateway:8080/eureka
  is2-runtime:
    image: mecdcme/is2-runtime:latest
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - 8085:8085
    environment:
      - SERVER_PORT=8085
      - SPRING_RABBITMQ_HOST=rabbitmq2
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres?currentSchema=is2
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_DATASOURCE_PLATFORM=postgresql
      - EUREKA_CLIENT_INSTANCE_HOSTNAME=eureka-server
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://is2-api-gateway:8080/eureka
  is2-design:
    image: mecdcme/is2-design:latest
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - 8086:8086
    environment:
      - SERVER_PORT=8086
      - SPRING_RABBITMQ_HOST=rabbitmq2
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres?currentSchema=is2
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_DATASOURCE_PLATFORM=postgresql
      - EUREKA_CLIENT_INSTANCE_HOSTNAME=eureka-server
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://is2-api-gateway:8080/eureka
