security:
  secret-key: is2-secretkey
server:
  port: 8080
spring:
  application:
    name: is2-api-gateway
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:mysql://localhost:3306/is2?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: bealu20092296
    driverClassName: com.mysql.cj.jdbc.Driver
    platform: mysql

zuul:
  routes:
    service_workflow_status:
      path: /api/monitor/**
      url: http://localhost:8081/monitor
    service_logger:
      path: /api/log/**
      url: http://localhost:8082/log
    service_dataset:
      path: /api/dataset/**
      url: http://localhost:8083/dataset
    service_notificator:
      path: /api/notificator/**
      url: http://localhost:8084/notificator
  include-debug-header: true

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
    server:
      waitTineInMsWhenSyncEmpty: 0
management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, auditevents
  metrics:
    export:
      atlas:
        enabled: false
